name: Format Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        id: format_check
        run: |
          # Turn off automatic exit on error
          set +e
          
          # Run the format check and capture the output
          cargo fmt --all -- --check > format_output.txt 2>&1
          FORMAT_EXIT_CODE=$?
          
          # Turn automatic exit on error back on
          set -e
          
          # Store the exit code for later steps
          echo "format_exit_code=$FORMAT_EXIT_CODE" >> $GITHUB_OUTPUT
          
          # Report results
          if [ $FORMAT_EXIT_CODE -ne 0 ]; then
            echo "⚠️ Formatting issues found:"
            cat format_output.txt
          else
            echo "✅ Code formatting looks good!"
          fi
          
          # Make sure we let the workflow continue to comment on PR
          exit 0
      
      - name: Comment PR with format issues
        if: github.event_name == 'pull_request' && steps.format_check.outputs.format_exit_code != '0'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('format_output.txt', 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "## ❌ Format Check Failed\n\nPlease run `cargo fmt` locally to fix formatting issues.\n\n```\n" + output + "\n```"
            });
      
      - name: Determine overall success
        if: always()
        run: |
          FORMAT_EXIT_CODE="${{ steps.format_check.outputs.format_exit_code }}"
          
          echo "Format exit code: $FORMAT_EXIT_CODE"
          
          if [[ "$FORMAT_EXIT_CODE" != "0" && "$FORMAT_EXIT_CODE" != "" ]]; then
            echo "::error::Code formatting issues found. Run 'cargo fmt' locally to fix."
            exit 1
          else
            echo "::notice::Format check completed successfully."
            exit 0
          fi 